package com.qionsi.simplification.material;

import java.util.HashMap;

import net.minecraftforge.fluids.FluidStack;

import com.qionsi.simplification.MyMod;

import bartworks.API.WerkstoffAdderRegistry;
import bartworks.system.material.Werkstoff;
import cpw.mods.fml.common.registry.LanguageRegistry;
import gregtech.api.enums.TextureSet;

/**
 * Registration of the five "Dimensionally Transcendent Catalyst" fluids of this mod.
 * <p>
 * Each entry is a Bartworks {@link Werkstoff} that only generates the liquid cell
 * ({@link Werkstoff.GenerationFeatures#addCells()}). GT/Bartworks then creates the fluid itself
 * ("autogenerated" texture, colour taken from the RGBA given here), the matching cell item and the
 * usual fluid <-> cell container recipes. Both the fluid and the cell use the localisation key
 * {@code Material.<lowercased internal name>}, which the {@link Werkstoff} constructor registers with
 * the English name automatically.
 * </p>
 * <p>
 * {@link #register()} is idempotent and must be called before Bartworks runs its werkstoff adders,
 * i.e. from the owning mod's preInit (see GTNL's {@code MaterialLoader.loadPreInit()} for the same
 * pattern). It is intentionally self contained: no existing file has to be modified.
 * </p>
 */
public class ModMaterials implements Runnable {

    /**
     * Werkstoff ids are shorts used as item metadata, so they must stay below 32768. Bartworks itself
     * uses 1-104, 3273 and 11500-11503, GTNL uses 25000-25202; this block sits above both.
     */
    private static final int ID_BASE = 25_900;

    private static final String ZH_CN = "zh_CN";

    private static final ModMaterials INSTANCE = new ModMaterials();

    private static boolean registered;

    public static Werkstoff DimensionallyTranscendentCrudeCatalyst;
    public static Werkstoff DimensionallyTranscendentMundaneCatalyst;
    public static Werkstoff DimensionallyTranscendentRadiantCatalyst;
    public static Werkstoff DimensionallyTranscendentAlienCatalyst;
    public static Werkstoff DimensionallyTranscendentStellarCatalyst;

    private ModMaterials() {}

    /**
     * Registers the five materials exactly once. Safe to call multiple times.
     */
    public static synchronized void register() {
        if (registered) return;
        registered = true;
        WerkstoffAdderRegistry.addWerkstoffAdder(INSTANCE);
    }

    @Override
    public void run() {
        DimensionallyTranscendentCrudeCatalyst = newFluidMaterial(
            "Dimensionally Transcendent Crude Catalyst",
            new short[] { 112, 64, 32 },
            ID_BASE + 1);
        DimensionallyTranscendentMundaneCatalyst = newFluidMaterial(
            "Dimensionally Transcendent Mundane Catalyst",
            new short[] { 144, 144, 144 },
            ID_BASE + 2);
        DimensionallyTranscendentRadiantCatalyst = newFluidMaterial(
            "Dimensionally Transcendent Radiant Catalyst",
            new short[] { 255, 224, 96 },
            ID_BASE + 3);
        DimensionallyTranscendentAlienCatalyst = newFluidMaterial(
            "Dimensionally Transcendent Alien Catalyst",
            new short[] { 128, 255, 128 },
            ID_BASE + 4);
        DimensionallyTranscendentStellarCatalyst = newFluidMaterial(
            "Dimensionally Transcendent Stellar Catalyst",
            new short[] { 96, 160, 255 },
            ID_BASE + 5);

        injectChineseNames();
    }

    /**
     * Writes what was actually created into the log: the id, the internal name (which is the basis of the localisation
     * key), the localisation key itself and whether a fluid exists for it. Called from the post-init, by which time
     * Bartworks has turned the werkstoffe into fluids and cells.
     */
    public static void logRegistration() {
        Werkstoff[] all = { DimensionallyTranscendentCrudeCatalyst, DimensionallyTranscendentMundaneCatalyst,
            DimensionallyTranscendentRadiantCatalyst, DimensionallyTranscendentAlienCatalyst,
            DimensionallyTranscendentStellarCatalyst };
        for (Werkstoff werkstoff : all) {
            if (werkstoff == null) {
                MyMod.LOG.error("A Dimensionally Transcendent Catalyst was never created; check the werkstoff ids.");
                continue;
            }
            FluidStack fluid = werkstoff.getFluidOrGas(1);
            MyMod.LOG.info(
                "Transcendent catalyst '{}': id {}, internal name '{}', language key '{}', fluid {}",
                werkstoff.getLocalizedNameKey(),
                werkstoff.getId(),
                werkstoff.getInternalName(),
                werkstoff.getLocalizedNameKey(),
                fluid == null ? "MISSING" : fluid.getUnlocalizedName() + " (" + fluid.amount + " mB)");
        }
    }

    private static Werkstoff newFluidMaterial(String englishName, short[] rgba, int id) {
        return new Werkstoff(
            rgba,
            englishName,
            "",
            new Werkstoff.Stats(),
            Werkstoff.Types.MATERIAL,
            new Werkstoff.GenerationFeatures().disable()
                .addCells(),
            id,
            TextureSet.SET_FLUID);
    }

    /**
     * Adds the Chinese display names for fluid and cell at runtime, without shipping a language file.
     * The keys are the ones the {@link Werkstoff} constructor uses for its own English registration.
     */
    private static void injectChineseNames() {
        HashMap<String, String> zhCN = new HashMap<>();
        zhCN.put(DimensionallyTranscendentCrudeCatalyst.getLocalizedNameKey(), "激发的粗制超维度催化剂");
        zhCN.put(DimensionallyTranscendentMundaneCatalyst.getLocalizedNameKey(), "激发的平凡超维度催化剂");
        zhCN.put(DimensionallyTranscendentRadiantCatalyst.getLocalizedNameKey(), "激发的光辉超维度催化剂");
        zhCN.put(DimensionallyTranscendentAlienCatalyst.getLocalizedNameKey(), "激发的异星超维度催化剂");
        zhCN.put(DimensionallyTranscendentStellarCatalyst.getLocalizedNameKey(), "激发的恒星超维度催化剂");
        LanguageRegistry.instance()
            .injectLanguage(ZH_CN, zhCN);
    }
}
